  try {
    console.log('внутри try до myVar');
    myVar;
     console.log('внутри try после myVar');

 } catch ( error) {
    console.log('Ошибка!');

 }
 console.log('после try...catch');








